import pandas as pd 
import numpy as np
print("--------------COLLECTING THE DATA--------------")
a={'Train Names':pd.Series(['Tamilnadu Express','Grand Trunk Express','NZM Kranthi Express','Janasatpadhi Express','Duronto Express','Sangmitra Express','Kerala Express','AP Express','PDY NDLS Express','Vande Bharat Express']),
   'Train Numbers':pd.Series([12621,12615,12651,12078,22203,12295,12625,20805,22403,20708]), 
   'Technical Supervisor (locopilot)':pd.Series(['Neha sood','Geeta Singh','Akash Kumar','Sartak sinha','Shiv Kumar','Mihir Krishnan','Asif pathan','Amit singh','Khvathi Kumari','Hashitha kaur']),
   'Station names':pd.Series(['Vijayawada','Delhi','Nizamudin','Guntur','Vijayawada','Danapur','Nagpur','Bhopal','Agra','Secundrabad']),
   'Payments':pd.Series([480,825,725,375,450,1780,970,520,800,1060]),
   'PNR':pd.Series([7823547901,9572456700,6305623899,7689087654,9876098334,8902357483,7843902365,9331122009,5367822309,8754632107]),
   'User Feedback':pd.Series([5,4,3,2,4,3,4,4,5,4])}
print("----------Pandas Packages - Series-----------")
b=pd.Series(a)
print(b)
print("----------------Data Frames-------------")
b=pd.DataFrame(a)
print(b)
print("-------------CRUD OPERATIONS--------------")
print("------------Create------------")
b['Ticket Status']=pd.Series(['Conform','Conform','Conform','RAC','RAC','Conform','Conform','RAC','Conform','Conform'])
print(b)
print("-------------Read--------------")
print(b['Train Names'])
print(b['Station names'][5])
print("-------------Update------------")
b.loc[0,'Train Numbers']=12220
print(b)
print("--------------Delete-------------")
b.pop('Ticket Status')
print(b)
print()
a={'Train Names':pd.Series(['Tamilnadu Express','Grand Trunk Express',np.nan,'Janasatpadhi Express','Duronto Express','Sangmitra Express',np.nan,'AP Express','PDY NDLS Express','Vande Bharat Express']),
   'Train Numbers':pd.Series([12621,np.nan,12651,12078,22203,12295,12625,20805,22403,20708]),
   'Technical Supervisor (locopilot)':pd.Series(['Neha sood','Geeta Singh','Akash Kumar','Sartak sinha',np.nan,'Mihir Krishnan','Asif pathan','Amit singh','Khvathi Kumari','Hashitha kaur']),
   'Station names':pd.Series([np.nan,'Delhi','Nizamudin','Guntur','Vijayawada','Danapur','Nagpur','Bhopal','Agra','Secundrabad']),
   'Payments':pd.Series([480,825,725,375,450,1780,np.nan,520,800,1060]),
   'PNR':pd.Series([7823547901,9572456700,np.nan,7689087654,9876098334,8902357483,7843902365,np.nan,5367822309,8754632107]),
   'User Feedback':pd.Series([np.nan,4,3,2,4,3,4,4,np.nan,4])}
b=pd.DataFrame(a)
print(b)
print("-------------------CLEANING DATA--------------")
print("-----------1. Empty data/Missing data----------")
print("------------------isnull()--------------------")
print(b.isnull())
print("---------------------notnull()----------------")
print(b.notnull())
print("------------2. Wrong Format Data------------------")
print("---------------dropna()------------------")
print(b.dropna())
print("-------------fillna(bfill)-------------")
print(b.bfill())
print("--------------fillna(pad)-------------")
print(b.ffill())
print("--------------fillna(100)--------------")
print(b.fillna(100))
print("---------------3.Remove Duplicates-----------")
print("-------------drop_duplicates-------------")
print(b.drop_duplicates())
print("-----------------info()---------------")
print(b.info())
print()
print("-------------DATA PREPROCESSING-----------------")
print(b.loc[1:6])
print("---------------------")
print(b.iloc[1:6])
print()
print("---------------ANALYZING THE DATA-----------------------")
print("-----------1. Head & Tail---------------")
print(b.head(5))
print()
print(b.tail(5))
print("-------------2. Data Ranking-------------")
print(b.rank())
print("-----------------3. Data Munging-------------")
print(b.isnull())
print()
print(b.notnull())
print("-------------4. Data Cleaning-------------")
print(b.bfill())
print()
print(b.ffill())
print()
print(b.fillna(100))
print("----------------5. Data Filtering--------------")
x=b.filter(['Train Names','Train Numbers'])
print(x)
print("--------------6. Data Aggregation--------------")
x=b.aggregate(['count'])
print(x)
print("--------------7. Data Reshaping-----------------")
print("reshape(2,7)")
print(a)
print()
print("-------------8. Data Grouping-----------------")
x=b.groupby(['Train Names','Station names','PNR'])
print(x.first())
